### ISSUE TITLE
[Feat] 슬랙 봇 알람 기능 구현

### ISSUE THREAD

**Issue by LWJ0513** [LWJ0513/coalitionhackathon2023#16]
## Description
인원이 다 차거나 모집 기간이 끝났을 때 알람을 보낸다.

- [ ] 알람을 한 번만 보내는지?
- [ ] 인원이 한 명만 추가되어도 알람을 보낼 건지? -> 디비 수정해야 함
- [ ] 인원이 줄어들어도 알람을 보낼 건지?
- [ ] 참여 취소 버튼 구현 됐는지? 
<br><br>

### Todo
- [ ] 
- [ ] 
- [ ]
